name: QA

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-scraper-qa:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml
          architecture: x64

      - name: Install dependencies (and project)
        run: |
          pip install -U pip
          pip install -e .[lint,scripts,test,check]

      - name: Check black formatting
        run: inv lint-black

      - name: Check ruff
        run: inv lint-ruff

      - name: Check pyright
        run: inv check-pyright

  check-zimui-qa:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: zimui/yarn.lock

      - name: Install zimui dependencies
        working-directory: zimui
        run: yarn install --frozen-lockfile

      - name: Check zimui formatting
        working-directory: zimui
        run: yarn format-check

      - name: Check zimui lint
        working-directory: zimui
        run: yarn lint-check
